/**
 * @vitest-environment happy-dom
 */
import { describe, expect, test } from "vitest";
import {
    jsonSchema2List,
    list2DefineList,
    list2JsonSchema,
    toJsonPlain,
    toJsonSchema,
} from "../Json2JsonSchema";
import { flatten, obj2Flatten } from "../JsonFlatten";

describe("JsonSchema测试", () => {
    describe("正常 ", () => {
        const model = {
            a: "234",
            d: { a: "234", b: 324, c: true },
            e: [
                { a: "234", b: 324, c: true },
                { a: "234", b: 324, c: true },
            ],
            f: [1, 2, 3],
            g: ["222", "333", "444"],
        };
        test("JSON 转Jsonschema", async () => {
            const item = toJsonSchema(model, {});
            console.log(JSON.stringify(item));
            expect(item.type).toBe("object");
            expect(item.properties?.a.type).toBe("string");
            expect(item.properties?.d.type).toBe("object");
            expect(item.properties?.e.type).toBe("array");
        });

        test(" List 转 FLatten", async () => {
            /*
            const itemList = [
                {
                    title: "根节点",
                    type: "object",
                    key: "root",
                    children: [
                        {
                            title: "[合同管理][铁销补充协议]",
                            type: "object",
                            key: "bus_con_rly_sup",
                            children: [
                                {
                                    title: "流程实例ID",
                                    type: "string",
                                    key: "actProcessInstanceId",
                                    description: "流程实例ID",
                                    children: [],
                                    id: "row_72",
                                },
                                {
                                    title: "流程状态",
                                    type: "string",
                                    key: "actProcessStatus",
                                    description: "流程状态",
                                    children: [],
                                    id: "row_73",
                                },
                                {
                                    title: "结算票数",
                                    type: "string",
                                    key: "balanceType",
                                    description: "结算票数",
                                    children: [],
                                    id: "row_74",
                                },
                                {
                                    title: "出卖人ID",
                                    type: "string",
                                    key: "bargainorId",
                                    description: "出卖人ID",
                                    children: [],
                                    id: "row_75",
                                },
                                {
                                    title: "是否重点合同",
                                    type: "string",
                                    key: "beImportant",
                                    description: "是否重点合同",
                                    children: [],
                                    id: "row_76",
                                },
                                {
                                    title: "是否预付款",
                                    type: "string",
                                    key: "bePrepaid",
                                    description: "是否预付款",
                                    children: [],
                                    id: "row_77",
                                },
                                {
                                    title: "是否包运费",
                                    type: "string",
                                    key: "beTocost",
                                    description: "是否包运费",
                                    children: [],
                                    id: "row_78",
                                },
                                {
                                    title: "煤炭贸易类型",
                                    type: "string",
                                    key: "coalTradeType",
                                    description: "煤炭贸易类型",
                                    children: [],
                                    id: "row_79",
                                },
                                {
                                    title: "合同铁销ID",
                                    type: "string",
                                    key: "conRlyId",
                                    description: "合同铁销ID",
                                    children: [],
                                    id: "row_80",
                                },
                                {
                                    title: "合同铁销-补充协议ID",
                                    type: "string",
                                    key: "conRlySupId",
                                    description: "合同铁销-补充协议ID",
                                    children: [],
                                    id: "row_81",
                                },
                                {
                                    title: "合同铁销-补充协议编码",
                                    type: "string",
                                    key: "conRlySupNo",
                                    description: "合同铁销-补充协议编码",
                                    children: [],
                                    id: "row_82",
                                },
                                {
                                    title: "客户编码[前缀]",
                                    type: "string",
                                    key: "conRlySupNoPrefix",
                                    description: "客户编码[前缀]",
                                    children: [],
                                    id: "row_83",
                                },
                                {
                                    title: "客户编码[流水]",
                                    type: "number",
                                    key: "conRlySupNoSerial",
                                    description: "客户编码[流水]",
                                    children: [],
                                    id: "row_84",
                                },
                                {
                                    title: "补充协议合同类型[年度,交易]",
                                    type: "string",
                                    key: "conRlySupType",
                                    description: "补充协议合同类型[年度,交易]",
                                    children: [],
                                    id: "row_85",
                                },
                                {
                                    title: "合同类型[年度,交易]",
                                    type: "string",
                                    key: "conRlyType",
                                    description: "合同类型[年度,交易]",
                                    children: [],
                                    id: "row_86",
                                },
                                {
                                    title: "年月份",
                                    type: "string",
                                    key: "conTime",
                                    description: "年月份",
                                    children: [],
                                    id: "row_87",
                                },
                                {
                                    title: "创建人账号",
                                    type: "string",
                                    key: "createId",
                                    description: "创建人账号",
                                    children: [],
                                    id: "row_88",
                                },
                                {
                                    title: "创建人名称",
                                    type: "string",
                                    key: "createName",
                                    description: "创建人名称",
                                    children: [],
                                    id: "row_89",
                                },
                                {
                                    title: "创建机构",
                                    type: "string",
                                    key: "createOrg",
                                    description: "创建机构",
                                    children: [],
                                    id: "row_90",
                                },
                                {
                                    title: "创建时间",
                                    type: "number",
                                    key: "createTimes",
                                    description: "创建时间",
                                    children: [],
                                    id: "row_91",
                                },
                                {
                                    title: "客户ID（买受人）",
                                    type: "string",
                                    key: "customerId",
                                    description: "客户ID（买受人）",
                                    children: [],
                                    id: "row_92",
                                },
                                {
                                    title: "逻辑删除0=删除,1=显示",
                                    type: "string",
                                    key: "delFlag",
                                    description: "逻辑删除0=删除,1=显示",
                                    children: [],
                                    id: "row_93",
                                },
                                {
                                    title: "备注",
                                    type: "string",
                                    key: "description",
                                    description: "备注",
                                    children: [],
                                    id: "row_94",
                                },
                                {
                                    title: "煤炭品种、质量约定（用于电子合同）",
                                    type: "string",
                                    key: "eleCoalQuality",
                                    description: "煤炭品种、质量约定（用于电子合同）",
                                    children: [],
                                    id: "row_95",
                                },
                                {
                                    title: "合同价格（用于电子合同）",
                                    type: "string",
                                    key: "eleConPrice",
                                    description: "合同价格（用于电子合同）",
                                    children: [],
                                    id: "row_96",
                                },
                                {
                                    title: "电子合同URL",
                                    type: "string",
                                    key: "eleContractUrl",
                                    description: "电子合同URL",
                                    children: [],
                                    id: "row_97",
                                },
                                {
                                    title: "收发货信息(用于电子合同)",
                                    type: "string",
                                    key: "eleSendTake",
                                    description: "收发货信息(用于电子合同)",
                                    children: [],
                                    id: "row_98",
                                },
                                {
                                    title: "结束时间",
                                    type: "string",
                                    key: "endTime",
                                    description: "结束时间",
                                    children: [],
                                    id: "row_99",
                                },
                                {
                                    title: "有效状态",
                                    type: "string",
                                    key: "flag",
                                    description: "有效状态",
                                    children: [],
                                    id: "row_100",
                                },
                                {
                                    title: "行业(字典)",
                                    type: "string",
                                    key: "industry",
                                    description: "行业(字典)",
                                    children: [],
                                    id: "row_101",
                                },
                                {
                                    title: "修改人账号",
                                    type: "string",
                                    key: "modifyId",
                                    description: "修改人账号",
                                    children: [],
                                    id: "row_102",
                                },
                                {
                                    title: "修改人名称",
                                    type: "string",
                                    key: "modifyName",
                                    description: "修改人名称",
                                    children: [],
                                    id: "row_103",
                                },
                                {
                                    title: "修改机构",
                                    type: "string",
                                    key: "modifyOrg",
                                    description: "修改机构",
                                    children: [],
                                    id: "row_104",
                                },
                                {
                                    title: "修改时间",
                                    type: "number",
                                    key: "modifyTimes",
                                    description: "修改时间",
                                    children: [],
                                    id: "row_105",
                                },
                                {
                                    title: "一月购销",
                                    type: "string",
                                    key: "month01Amount",
                                    description: "一月购销",
                                    children: [],
                                    id: "row_106",
                                },
                                {
                                    title: "二月购销",
                                    type: "string",
                                    key: "month02Amount",
                                    description: "二月购销",
                                    children: [],
                                    id: "row_107",
                                },
                                {
                                    title: "三月购销",
                                    type: "string",
                                    key: "month03Amount",
                                    description: "三月购销",
                                    children: [],
                                    id: "row_108",
                                },
                                {
                                    title: "四月购销",
                                    type: "string",
                                    key: "month04Amount",
                                    description: "四月购销",
                                    children: [],
                                    id: "row_109",
                                },
                                {
                                    title: "五月购销",
                                    type: "string",
                                    key: "month05Amount",
                                    description: "五月购销",
                                    children: [],
                                    id: "row_110",
                                },
                                {
                                    title: "六月购销",
                                    type: "string",
                                    key: "month06Amount",
                                    description: "六月购销",
                                    children: [],
                                    id: "row_111",
                                },
                                {
                                    title: "七月购销",
                                    type: "string",
                                    key: "month07Amount",
                                    description: "七月购销",
                                    children: [],
                                    id: "row_112",
                                },
                                {
                                    title: "八月购销",
                                    type: "string",
                                    key: "month08Amount",
                                    description: "八月购销",
                                    children: [],
                                    id: "row_113",
                                },
                                {
                                    title: "九月购销",
                                    type: "string",
                                    key: "month09Amount",
                                    description: "九月购销",
                                    children: [],
                                    id: "row_114",
                                },
                                {
                                    title: "十月购销",
                                    type: "string",
                                    key: "month10Amount",
                                    description: "十月购销",
                                    children: [],
                                    id: "row_115",
                                },
                                {
                                    title: "十一月购销",
                                    type: "string",
                                    key: "month11Amount",
                                    description: "十一月购销",
                                    children: [],
                                    id: "row_116",
                                },
                                {
                                    title: "十二月购销",
                                    type: "string",
                                    key: "month12Amount",
                                    description: "十二月购销",
                                    children: [],
                                    id: "row_117",
                                },
                                {
                                    title: "关联机构",
                                    type: "string",
                                    key: "orgId",
                                    description: "关联机构",
                                    children: [],
                                    id: "row_118",
                                },
                                {
                                    title: "第三方(客户)ID",
                                    type: "string",
                                    key: "participateCustomerId",
                                    description: "第三方(客户)ID",
                                    children: [],
                                    id: "row_119",
                                },
                                {
                                    title: "计划标志",
                                    type: "string",
                                    key: "planMark",
                                    description: "计划标志",
                                    children: [],
                                    id: "row_120",
                                },
                                {
                                    title: "所属区域",
                                    type: "string",
                                    key: "regionlId",
                                    description: "所属区域",
                                    children: [],
                                    id: "row_121",
                                },
                                {
                                    title: "购销总量(吨)",
                                    type: "string",
                                    key: "saleSumAmount",
                                    description: "购销总量(吨)",
                                    children: [],
                                    id: "row_122",
                                },
                                {
                                    title: "购销类型",
                                    type: "string",
                                    key: "saleType",
                                    description: "购销类型",
                                    children: [],
                                    id: "row_123",
                                },
                                {
                                    title: "签订地点",
                                    type: "string",
                                    key: "signedPlace",
                                    description: "签订地点",
                                    children: [],
                                    id: "row_124",
                                },
                                {
                                    title: "签订日期",
                                    type: "string",
                                    key: "signedTime",
                                    description: "签订日期",
                                    children: [],
                                    id: "row_125",
                                },
                                {
                                    title: "货源类型",
                                    type: "string",
                                    key: "sourceType",
                                    description: "货源类型",
                                    children: [],
                                    id: "row_126",
                                },
                                {
                                    title: "开始时间",
                                    type: "string",
                                    key: "startTime",
                                    description: "开始时间",
                                    children: [],
                                    id: "row_127",
                                },
                                {
                                    title: "合同状态",
                                    type: "string",
                                    key: "state",
                                    description: "合同状态",
                                    children: [],
                                    id: "row_128",
                                },
                                {
                                    title: "列表树ID",
                                    type: "string",
                                    key: "tableTreeId",
                                    description: "列表树ID",
                                    children: [],
                                    id: "row_129",
                                },
                                {
                                    title: "是否垫付运费",
                                    type: "string",
                                    key: "transportTyp",
                                    description: "是否垫付运费",
                                    children: [],
                                    id: "row_130",
                                },
                                {
                                    title: "运输方式",
                                    type: "string",
                                    key: "transportationType",
                                    description: "运输方式",
                                    children: [],
                                    id: "row_131",
                                },
                                {
                                    title: "版本号",
                                    type: "number",
                                    key: "versions",
                                    description: "版本号",
                                    children: [],
                                    id: "row_132",
                                },
                                {
                                    title: "年合同或月合同",
                                    type: "string",
                                    key: "yearMonthTime",
                                    description: "年合同或月合同",
                                    children: [],
                                    id: "row_133",
                                },
                                {
                                    title: "贸易合同类型（年度/日常）",
                                    type: "string",
                                    key: "yearOrDaily",
                                    description: "贸易合同类型（年度/日常）",
                                    children: [],
                                    id: "row_134",
                                },
                            ],
                            id: "row_71",
                        },
                        {
                            title: "[合同管理][铁销补充协议][供货煤种信息]",
                            type: "object",
                            key: "bus_con_rly_sup_coal",
                            children: [
                                {
                                    title: "铁销先款后货ID",
                                    type: "string",
                                    key: "advancePaymentId",
                                    description: "铁销先款后货ID",
                                    children: [],
                                    id: "row_136",
                                },
                                {
                                    title: "铁销热值奖惩ID",
                                    type: "string",
                                    key: "chastenId",
                                    description: "铁销热值奖惩ID",
                                    children: [],
                                    id: "row_137",
                                },
                                {
                                    title: "煤种ID",
                                    type: "string",
                                    key: "coalTypeId",
                                    description: "煤种ID",
                                    children: [],
                                    id: "row_138",
                                },
                                {
                                    title: "品种ID",
                                    type: "string",
                                    key: "coalVarietyId",
                                    description: "品种ID",
                                    children: [],
                                    id: "row_139",
                                },
                                {
                                    title: "合同铁销-补充ID",
                                    type: "string",
                                    key: "conRlySupId",
                                    description: "合同铁销-补充ID",
                                    children: [],
                                    id: "row_140",
                                },
                                {
                                    title: "创建人账号",
                                    type: "string",
                                    key: "createId",
                                    description: "创建人账号",
                                    children: [],
                                    id: "row_141",
                                },
                                {
                                    title: "创建人名称",
                                    type: "string",
                                    key: "createName",
                                    description: "创建人名称",
                                    children: [],
                                    id: "row_142",
                                },
                                {
                                    title: "创建时间",
                                    type: "number",
                                    key: "createTimes",
                                    description: "创建时间",
                                    children: [],
                                    id: "row_143",
                                },
                                {
                                    title: "描述",
                                    type: "string",
                                    key: "description",
                                    description: "描述",
                                    children: [],
                                    id: "row_144",
                                },
                                {
                                    title: "铁销内部企业ID",
                                    type: "string",
                                    key: "internalEnterpriseId",
                                    description: "铁销内部企业ID",
                                    children: [],
                                    id: "row_145",
                                },
                                {
                                    title: "灰分检测值",
                                    type: "string",
                                    key: "iqcAd",
                                    description: "灰分检测值",
                                    children: [],
                                    id: "row_146",
                                },
                                {
                                    title: "粘结指数检测值",
                                    type: "string",
                                    key: "iqcGr",
                                    description: "粘结指数检测值",
                                    children: [],
                                    id: "row_147",
                                },
                                {
                                    title: "氢检测值",
                                    type: "string",
                                    key: "iqcHad",
                                    description: "氢检测值",
                                    children: [],
                                    id: "row_148",
                                },
                                {
                                    title: "分析水检测值",
                                    type: "string",
                                    key: "iqcMad",
                                    description: "分析水检测值",
                                    children: [],
                                    id: "row_149",
                                },
                                {
                                    title: "全水分检测值",
                                    type: "string",
                                    key: "iqcMt",
                                    description: "全水分检测值",
                                    children: [],
                                    id: "row_150",
                                },
                                {
                                    title: "其他检测值",
                                    type: "string",
                                    key: "iqcOther",
                                    description: "其他检测值",
                                    children: [],
                                    id: "row_151",
                                },
                                {
                                    title: "发热量检测值",
                                    type: "string",
                                    key: "iqcQnet",
                                    description: "发热量检测值",
                                    children: [],
                                    id: "row_152",
                                },
                                {
                                    title: "全硫检测值",
                                    type: "string",
                                    key: "iqcSt",
                                    description: "全硫检测值",
                                    children: [],
                                    id: "row_153",
                                },
                                {
                                    title: "挥发分检测值",
                                    type: "string",
                                    key: "iqcVdaf",
                                    description: "挥发分检测值",
                                    children: [],
                                    id: "row_154",
                                },
                                {
                                    title: "修改人账号",
                                    type: "string",
                                    key: "modifyId",
                                    description: "修改人账号",
                                    children: [],
                                    id: "row_155",
                                },
                                {
                                    title: "修改人名称",
                                    type: "string",
                                    key: "modifyName",
                                    description: "修改人名称",
                                    children: [],
                                    id: "row_156",
                                },
                                {
                                    title: "修改时间",
                                    type: "number",
                                    key: "modifyTimes",
                                    description: "修改时间",
                                    children: [],
                                    id: "row_157",
                                },
                                {
                                    title: "基础价格ID",
                                    type: "string",
                                    key: "priceRlyBaseId",
                                    description: "基础价格ID",
                                    children: [],
                                    id: "row_158",
                                },
                                {
                                    title: "价格策略ID",
                                    type: "string",
                                    key: "priceRlyStratId",
                                    description: "价格策略ID",
                                    children: [],
                                    id: "row_159",
                                },
                                {
                                    title: "基础价格值",
                                    type: "string",
                                    key: "priceValue",
                                    description: "基础价格值",
                                    children: [],
                                    id: "row_160",
                                },
                                {
                                    title: "质量指标IDS",
                                    type: "string",
                                    key: "qualityIndexIds",
                                    description: "质量指标IDS",
                                    children: [],
                                    id: "row_161",
                                },
                                {
                                    title: "质量指标名称S",
                                    type: "string",
                                    key: "qualityIndexNames",
                                    description: "质量指标名称S",
                                    children: [],
                                    id: "row_162",
                                },
                                {
                                    title: "铁销兑现率优惠ID",
                                    type: "string",
                                    key: "redemptionRateId",
                                    description: "铁销兑现率优惠ID",
                                    children: [],
                                    id: "row_163",
                                },
                                {
                                    title: "供货煤种信息ID",
                                    type: "string",
                                    key: "rlySupCoalId",
                                    description: "供货煤种信息ID",
                                    children: [],
                                    id: "row_164",
                                },
                                {
                                    title: "版本号",
                                    type: "number",
                                    key: "versions",
                                    description: "版本号",
                                    children: [],
                                    id: "row_165",
                                },
                                {
                                    title: "铁销量价优惠ID",
                                    type: "string",
                                    key: "volumeId",
                                    description: "铁销量价优惠ID",
                                    children: [],
                                    id: "row_166",
                                },
                            ],
                            id: "row_135",
                        },
                        {
                            title: "[合同管理][铁销补充协议][收货信息]",
                            type: "object",
                            key: "bus_con_rly_sup_take",
                            children: [
                                {
                                    title: "合同铁销-补充ID",
                                    type: "string",
                                    key: "conRlySupId",
                                    description: "合同铁销-补充ID",
                                    children: [],
                                    id: "row_168",
                                },
                                {
                                    title: "创建人账号",
                                    type: "string",
                                    key: "createId",
                                    description: "创建人账号",
                                    children: [],
                                    id: "row_169",
                                },
                                {
                                    title: "创建人名称",
                                    type: "string",
                                    key: "createName",
                                    description: "创建人名称",
                                    children: [],
                                    id: "row_170",
                                },
                                {
                                    title: "创建时间",
                                    type: "number",
                                    key: "createTimes",
                                    description: "创建时间",
                                    children: [],
                                    id: "row_171",
                                },
                                {
                                    title: "客户ID",
                                    type: "string",
                                    key: "customerId",
                                    description: "客户ID",
                                    children: [],
                                    id: "row_172",
                                },
                                {
                                    title: "描述",
                                    type: "string",
                                    key: "description",
                                    description: "描述",
                                    children: [],
                                    id: "row_173",
                                },
                                {
                                    title: "专线ID",
                                    type: "string",
                                    key: "lineId",
                                    description: "专线ID",
                                    children: [],
                                    id: "row_174",
                                },
                                {
                                    title: "联系人名称",
                                    type: "string",
                                    key: "linkmanName",
                                    description: "联系人名称",
                                    children: [],
                                    id: "row_175",
                                },
                                {
                                    title: "联系人电话",
                                    type: "string",
                                    key: "linkmanPhone",
                                    description: "联系人电话",
                                    children: [],
                                    id: "row_176",
                                },
                                {
                                    title: "修改人账号",
                                    type: "string",
                                    key: "modifyId",
                                    description: "修改人账号",
                                    children: [],
                                    id: "row_177",
                                },
                                {
                                    title: "修改人名称",
                                    type: "string",
                                    key: "modifyName",
                                    description: "修改人名称",
                                    children: [],
                                    id: "row_178",
                                },
                                {
                                    title: "修改时间",
                                    type: "number",
                                    key: "modifyTimes",
                                    description: "修改时间",
                                    children: [],
                                    id: "row_179",
                                },
                                {
                                    title: "合同铁销-补充:收货信息ID",
                                    type: "string",
                                    key: "rlySupTakeId",
                                    description: "合同铁销-补充:收货信息ID",
                                    children: [],
                                    id: "row_180",
                                },
                                {
                                    title: "站点ID",
                                    type: "string",
                                    key: "standId",
                                    description: "站点ID",
                                    children: [],
                                    id: "row_181",
                                },
                                {
                                    title: "收货地址ID",
                                    type: "string",
                                    key: "takeId",
                                    description: "收货地址ID",
                                    children: [],
                                    id: "row_182",
                                },
                                {
                                    title: "收货地址",
                                    type: "string",
                                    key: "takeName",
                                    description: "收货地址",
                                    children: [],
                                    id: "row_183",
                                },
                                {
                                    title: "版本号",
                                    type: "number",
                                    key: "versions",
                                    description: "版本号",
                                    children: [],
                                    id: "row_184",
                                },
                            ],
                            id: "row_167",
                        },
                        {
                            title: "[合同管理][铁销补充协议][附件信息]",
                            type: "object",
                            key: "bus_con_rly_sup_file",
                            children: [
                                {
                                    title: "合同铁销编号",
                                    type: "string",
                                    key: "conRlySupId",
                                    description: "合同铁销编号",
                                    children: [],
                                    id: "row_186",
                                },
                                {
                                    title: "创建人账号",
                                    type: "string",
                                    key: "createId",
                                    description: "创建人账号",
                                    children: [],
                                    id: "row_187",
                                },
                                {
                                    title: "创建人名称",
                                    type: "string",
                                    key: "createName",
                                    description: "创建人名称",
                                    children: [],
                                    id: "row_188",
                                },
                                {
                                    title: "创建时间",
                                    type: "number",
                                    key: "createTimes",
                                    description: "创建时间",
                                    children: [],
                                    id: "row_189",
                                },
                                {
                                    title: "合同铁销:附件编号",
                                    type: "string",
                                    key: "fileId",
                                    description: "合同铁销:附件编号",
                                    children: [],
                                    id: "row_190",
                                },
                                {
                                    title: "文件名称",
                                    type: "string",
                                    key: "fileName",
                                    description: "文件名称",
                                    children: [],
                                    id: "row_191",
                                },
                                {
                                    title: "文件服务",
                                    type: "string",
                                    key: "fileServer",
                                    description: "文件服务",
                                    children: [],
                                    id: "row_192",
                                },
                                {
                                    title: "文件大小",
                                    type: "string",
                                    key: "fileSize",
                                    description: "文件大小",
                                    children: [],
                                    id: "row_193",
                                },
                                {
                                    title: "文件后缀",
                                    type: "string",
                                    key: "fileSuffix",
                                    description: "文件后缀",
                                    children: [],
                                    id: "row_194",
                                },
                                {
                                    title: "文件类型",
                                    type: "string",
                                    key: "fileType",
                                    description: "文件类型",
                                    children: [],
                                    id: "row_195",
                                },
                                {
                                    title: "文件路径",
                                    type: "string",
                                    key: "fileUrl",
                                    description: "文件路径",
                                    children: [],
                                    id: "row_196",
                                },
                                {
                                    title: "修改人账号",
                                    type: "string",
                                    key: "modifyId",
                                    description: "修改人账号",
                                    children: [],
                                    id: "row_197",
                                },
                                {
                                    title: "修改人名称",
                                    type: "string",
                                    key: "modifyName",
                                    description: "修改人名称",
                                    children: [],
                                    id: "row_198",
                                },
                                {
                                    title: "修改时间",
                                    type: "number",
                                    key: "modifyTimes",
                                    description: "修改时间",
                                    children: [],
                                    id: "row_199",
                                },
                                {
                                    title: "版本号",
                                    type: "number",
                                    key: "versions",
                                    description: "版本号",
                                    children: [],
                                    id: "row_200",
                                },
                                {
                                    title: "序号",
                                    type: "string",
                                    key: "weightOrder",
                                    description: "序号",
                                    children: [],
                                    id: "row_201",
                                },
                            ],
                            id: "row_185",
                        },
                        {
                            title: "[合同管理][铁销补充协议][供货信息]",
                            type: "object",
                            key: "bus_con_rly_sup_send",
                            children: [
                                {
                                    title: "合同铁销-补充ID",
                                    type: "string",
                                    key: "conRlySupId",
                                    description: "合同铁销-补充ID",
                                    children: [],
                                    id: "row_203",
                                },
                                {
                                    title: "创建人账号",
                                    type: "string",
                                    key: "createId",
                                    description: "创建人账号",
                                    children: [],
                                    id: "row_204",
                                },
                                {
                                    title: "创建人名称",
                                    type: "string",
                                    key: "createName",
                                    description: "创建人名称",
                                    children: [],
                                    id: "row_205",
                                },
                                {
                                    title: "创建时间",
                                    type: "number",
                                    key: "createTimes",
                                    description: "创建时间",
                                    children: [],
                                    id: "row_206",
                                },
                                {
                                    title: "交货地址",
                                    type: "string",
                                    key: "deliveryAddress",
                                    description: "交货地址",
                                    children: [],
                                    id: "row_207",
                                },
                                {
                                    title: "交货方式",
                                    type: "string",
                                    key: "deliveryWay",
                                    description: "交货方式",
                                    children: [],
                                    id: "row_208",
                                },
                                {
                                    title: "描述",
                                    type: "string",
                                    key: "description",
                                    description: "描述",
                                    children: [],
                                    id: "row_209",
                                },
                                {
                                    title: "专线ID",
                                    type: "string",
                                    key: "lineId",
                                    description: "专线ID",
                                    children: [],
                                    id: "row_210",
                                },
                                {
                                    title: "联系人名称",
                                    type: "string",
                                    key: "linkmanName",
                                    description: "联系人名称",
                                    children: [],
                                    id: "row_211",
                                },
                                {
                                    title: "联系人电话",
                                    type: "string",
                                    key: "linkmanPhone",
                                    description: "联系人电话",
                                    children: [],
                                    id: "row_212",
                                },
                                {
                                    title: "修改人账号",
                                    type: "string",
                                    key: "modifyId",
                                    description: "修改人账号",
                                    children: [],
                                    id: "row_213",
                                },
                                {
                                    title: "修改人名称",
                                    type: "string",
                                    key: "modifyName",
                                    description: "修改人名称",
                                    children: [],
                                    id: "row_214",
                                },
                                {
                                    title: "修改时间",
                                    type: "number",
                                    key: "modifyTimes",
                                    description: "修改时间",
                                    children: [],
                                    id: "row_215",
                                },
                                {
                                    title: "供货信息ID",
                                    type: "string",
                                    key: "rlySupSendId",
                                    description: "供货信息ID",
                                    children: [],
                                    id: "row_216",
                                },
                                {
                                    title: "发货地址ID",
                                    type: "string",
                                    key: "sendAddressId",
                                    description: "发货地址ID",
                                    children: [],
                                    id: "row_217",
                                },
                                {
                                    title: "发货地址",
                                    type: "string",
                                    key: "sendAddressName",
                                    description: "发货地址",
                                    children: [],
                                    id: "row_218",
                                },
                                {
                                    title: "发货人名称",
                                    type: "string",
                                    key: "sender",
                                    description: "发货人名称",
                                    children: [],
                                    id: "row_219",
                                },
                                {
                                    title: "站点ID",
                                    type: "string",
                                    key: "standId",
                                    description: "站点ID",
                                    children: [],
                                    id: "row_220",
                                },
                                {
                                    title: "供货单位ID",
                                    type: "string",
                                    key: "supplierId",
                                    description: "供货单位ID",
                                    children: [],
                                    id: "row_221",
                                },
                                {
                                    title: "版本号",
                                    type: "number",
                                    key: "versions",
                                    description: "版本号",
                                    children: [],
                                    id: "row_222",
                                },
                            ],
                            id: "row_202",
                        },
                    ],
                    id: "row_70",
                },
            ];
            */
            const itemList = {
                type: "object",
                title: "Params根节点",
                properties: {
                    "Obj[]": {
                        items: {
                            type: "object",
                            properties: {
                                attr1: {
                                    type: "string",
                                    title: "attr1",
                                },
                                attr2: {
                                    type: "string",
                                    title: "attr2",
                                },
                                attr3: {
                                    type: "string",
                                    title: "attr3",
                                },
                                attr4: {
                                    type: "string",
                                    title: "attr4",
                                },
                                attr5: {
                                    type: "string",
                                    title: "attr5",
                                },
                                attr6: {
                                    type: "string",
                                    title: "attr6",
                                },
                            },
                            title: "items",
                        },
                        type: "array",
                        title: "Obj[]",
                    },
                },
            };
            const list = jsonSchema2List(itemList, {});
            console.log(list);
            const defines = list2DefineList(list, {});
            console.log(defines);
        });

        test("obj转FLatten", async () => {
            const itemList = {
                attrC: "attrC0",
                secondFloorA: {
                    attrA: "attrA1",
                    attrB: "attrB1",
                    attrC: "attrC1",
                },
                secondFloorB: {
                    attrA: "attrA2",
                    attrB: "attrB2",
                    attrC: "attrC2",
                },
                ddd: {
                    attrA: "attrA2d",
                    attrB: "attrB2d",
                    attrC: "attrC2d",
                },
                bus_sal_bargainor: {
                    attrA: "attrA2d_bargainor",
                    attrB: "attrB2d_bargainor",
                    attrC: "attrC2d_bargainor",
                },
                bus_cus_customer_group: {
                    attrA: "attrA2d_customer",
                    attrB: "attrB2d_customer",
                    attrC: "attrC2d_customer",
                },
                send: [
                    {
                        attrA: 1,
                        attrB: 2,
                        attrC: 3,
                    },
                ],
            };
            const result = obj2Flatten(
                itemList,
                ["secondFloorA.attrA", "secondFloorA.attrB", "secondFloorB.attrA", "secondFloorB.attrB"],
                ["firstA", "firstB", "secondA", "secondB"],
                ["attrC"]
            );
            // const result = obj2Flatten(itemList)
            // const result = flatten(itemList)
            console.log(result);
        });

        test("List转JsonSchema ", async () => {
            const item = {
                type: "object",
                properties: {
                    code: {
                        type: "string",
                        description: "代码",
                    },
                },
                additionalProperties: false,
                description: "sys_dict_value，数据字典值",
                title: "数据字典值",
            };
            const itemList = jsonSchema2List(item, {});
            const item2 = list2JsonSchema(itemList, {});
            console.log(JSON.stringify(item2));
        });
        test("List转JsonValue ", async () => {
            const item = {
                type: "object",
                title: "根节点",
                properties: {
                    bus_sal_coal_variety_parent: {
                        type: "object",
                        properties: {
                            coalVarietyParentId: {
                                type: "string",
                                title: "品种父级ID",
                                description: "品种父级ID",
                            },
                            coalVarietyParentName: {
                                type: "string",
                                title: "品种父级名称",
                                description: "品种父级名称",
                            },
                            coalVarietyParentNo: {
                                type: "string",
                                title: "品种父级代码",
                                description: "品种父级代码",
                            },
                            createId: {
                                type: "string",
                                title: "创建人账号",
                                description: "创建人账号",
                            },
                            createName: {
                                type: "string",
                                title: "创建人名称",
                                description: "创建人名称",
                            },
                            createTimes: {
                                type: "number",
                                title: "创建时间",
                                description: "创建时间",
                            },
                            modifyId: {
                                type: "string",
                                title: "修改人账号",
                                description: "修改人账号",
                            },
                            modifyName: {
                                type: "string",
                                title: "修改人名称",
                                description: "修改人名称",
                            },
                            modifyTimes: {
                                type: "number",
                                title: "修改时间",
                                description: "修改时间",
                            },
                            versions: {
                                type: "number",
                                title: "版本号",
                                description: "版本号",
                            },
                        },
                        title: "[基础数据]品种父级_bus_sal_coal_variety_parent",
                    },
                    bus_sal_coal_type: {
                        type: "object",
                        properties: {
                            coalTypeId: {
                                type: "string",
                                title: "煤种编号",
                                description: "煤种编号",
                            },
                            coalTypeName: {
                                type: "string",
                                title: "煤种名称",
                                description: "煤种名称",
                            },
                            coalTypeNo: {
                                type: "string",
                                title: "煤种代码",
                                description: "煤种代码",
                            },
                            coalTypeParentId: {
                                type: "string",
                                title: "父级煤种ID",
                                description: "父级煤种ID",
                            },
                            createId: {
                                type: "string",
                                title: "创建人账号",
                                description: "创建人账号",
                            },
                            createName: {
                                type: "string",
                                title: "创建人名称",
                                description: "创建人名称",
                            },
                            createTimes: {
                                type: "number",
                                title: "创建时间",
                                description: "创建时间",
                            },
                            description: {
                                type: "string",
                                title: "描述",
                                description: "描述",
                            },
                            modifyId: {
                                type: "string",
                                title: "修改人账号",
                                description: "修改人账号",
                            },
                            modifyName: {
                                type: "string",
                                title: "修改人名称",
                                description: "修改人名称",
                            },
                            modifyTimes: {
                                type: "number",
                                title: "修改时间",
                                description: "修改时间",
                            },
                            versions: {
                                type: "number",
                                title: "版本号",
                                description: "版本号",
                            },
                            weightOrder: {
                                type: "number",
                                title: "排序权重",
                                description: "排序权重",
                            },
                        },
                        title: "[基础数据]煤种_bus_sal_coal_type",
                    },
                },
            };
            const itemList = jsonSchema2List(item, {});
            const item2 = toJsonPlain(itemList, {});
            console.log(item2);
        });
    });
});
